### ISSUE TITLE
Discord link does not work

### ISSUE THREAD

**Issue by SilverSoggy** [Daomephsta/LootTweaker-Docs#4]
I want to get some help on your discord server but link is just broken. Can you update it?
also i had some problems using looty tables, the example code from the dev does not work.

import crafttweaker.entity.IEntityDropFunction;

import loottweaker.vanilla.loot.LootTables;
import loottweaker.vanilla.loot.LootTable;
import loottweaker.vanilla.loot.LootPool;
import loottweaker.vanilla.loot.Conditions;
import loottweaker.vanilla.loot.Functions;

val chest1 = LootTables.getTable("neuroflow:chests/chestloot1");
val main = chest1.getPool("main");
main.clearEntries();
val c1p1 = chest1.addPool("c1p1", 1, 3, 0, 2);
c1p1.addItemEntry(<minecraft:string>, 5);

here it is. I always had huge problems with docs so it will be very nice if you help me.

**Comment by SilverSoggy** [comment]
Also i know that instead of LootTables.getTable you should write LootTweaker.getTable, but in any case it does not work.

**Comment by Daomephsta** [comment]
When asking for help, you have all the information, so it's quite easy to forget the person helping you doesn't, and not include important information. Following this template helps avoid that:
* What you did
* What you expected to happen
* What actually happened (even if nothing happened, that's useful information)



For example rather than saying the invite link is broken; it would be useful to tell me that when you clicked it, you were redirected to discord.com; or redirected to an invalid invite page; or whatever happened when you clicked the link.  

> I always had huge problems with docs

Many people do. Very few of them say anything about it, and fewer explain beyond "they're confusing". So the docs stay the way they are, because nobody tells me what needs to be clarified.

As for your code issues, "doesn't work" is too vague to help. Follow the template and I can help you.

**Comment by Daomephsta** [comment]
Also generally you should create one issue per set of related problems. This is an issue tracker. It's much less useful if unrelated problems are one issue on the tracker.

**Comment by Daomephsta** [comment]
Looking into Looty Tables, it's redundant. LootTweaker has been able to create new tables since version 0.2.0.
Use `LootTweaker.newTable`. See https://loottweaker-docs.readthedocs.io/en/latest/type-docs/loottweaker.html#zenfunction-newTable(String) for docs and an example. It works much like `LootTweaker.getTable`
